<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="<?= DEFAULT_IMAGE_PATH . 'user-image.png'?>" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info d-block text-white">
                Jovane
            </div>
        </div>
    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
      
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                    with font-awesome or any other icon font library -->
                <li class="nav-item has-treeview nav-item-click cp">
                    <a class="nav-link">
                        <i class="nav-icon fas fa-cog"></i>
                        <p>
                            OS
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="./index.html" class="nav-link">
                                <i class="fas fa-chevron-right nav-icon"></i>
                                <p>Adicionar OS</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="./index.html" class="nav-link">
                                <i class="fas fa-chevron-right nav-icon"></i>
                                <p>Em aberto</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="./index2.html" class="nav-link">
                                <i class="fas fa-chevron-right nav-icon"></i>
                                <p>Fechadas</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="./index3.html" class="nav-link">
                                <i class="fas fa-chevron-right nav-icon"></i>
                                <p>Pendentes</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="./index3.html" class="nav-link">
                                <i class="fas fa-chevron-right nav-icon"></i>
                                <p>Todas</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item has-treeview nav-item-click cp">
                    <a class="nav-link    ">
                        <i class="nav-icon fas fa-th"></i>
                        <p>
                            Orçamento
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="orcamento-adicionar" class="nav-link">
                                <i class="fas fa-chevron-right nav-icon"></i>
                                <p>Adicionar</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="./index.html" class="nav-link">
                                <i class="fas fa-chevron-right nav-icon"></i>
                                <p>Em aberto</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="./index2.html" class="nav-link">
                                <i class="fas fa-chevron-right nav-icon"></i>
                                <p>Fechados</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="./index3.html" class="nav-link">
                                <i class="fas fa-chevron-right nav-icon"></i>
                                <p>Pendentes</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="./index3.html" class="nav-link">
                                <i class="fas fa-chevron-right nav-icon"></i>
                                <p>Todas</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item has-treeview nav-item-click cp">
                    <a class="nav-link">
                        <i class="nav-icon fas fa-dollar-sign"></i>
                        <p>
                            Pagamentos
                            <i class="fas fa-angle-left right"></i>
                            <span class="badge badge-info right">6</span>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="pages/layout/top-nav.html" class="nav-link">
                                <i class="fas fa-chevron-right nav-icon"></i>
                                <p>Top Navigation</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="pages/layout/boxed.html" class="nav-link">
                                <i class="fas fa-chevron-right nav-icon"></i>
                                <p>Boxed</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="pages/layout/fixed-sidebar.html" class="nav-link">
                                <i class="fas fa-chevron-right nav-icon"></i>
                                <p>Fixed Sidebar</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="pages/layout/fixed-topnav.html" class="nav-link">
                                <i class="fas fa-chevron-right nav-icon"></i>
                                <p>Fixed Navbar</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="pages/layout/fixed-footer.html" class="nav-link">
                                <i class="fas fa-chevron-right nav-icon"></i>
                                <p>Fixed Footer</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="pages/layout/collapsed-sidebar.html" class="nav-link">
                                <i class="fas fa-chevron-right nav-icon"></i>
                                <p>Collapsed Sidebar</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <!-- Clients -->
                <li class="nav-item has-treeview nav-item-click cp">
                    <a class="nav-link">
                        <i class="nav-icon fas fa-users"></i>
                        <p>
                            Clientes
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="cliente-adicionar" class="nav-link">
                                <i class="fas fa-chevron-right nav-icon"></i>
                                <p>Adicionar</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="pages/layout/boxed.html" class="nav-link">
                                <i class="fas fa-chevron-right nav-icon"></i>
                                <p>Consultar</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <!-- /.Clientes -->

                <!-- Users -->
                <li class="nav-item has-treeview nav-item-click cp">
                    <a class="nav-link">
                        <i class="nav-icon fas fa-user"></i>
                        <p>
                            Usuários
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="pages/layout/top-nav.html" class="nav-link">
                                <i class="fas fa-chevron-right nav-icon"></i>
                                <p>Adicionar</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="pages/layout/boxed.html" class="nav-link">
                                <i class="fas fa-chevron-right nav-icon"></i>
                                <p>Excluir</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <!-- /.Users -->

                <!-- Contact -->
                <li class="nav-item nav-item-click cp">
                    <a class="nav-link">
                        <i class="nav-icon fas fa-envelope-square"></i>
                        <p>
                            Contato
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                </li>
                <!-- /.Users -->

                <!-- Contact -->
                <li class="nav-item nav-item-click cp">
                    <a class="nav-link">
                        <i class="nav-icon fas fa-exclamation-triangle"></i>
                        <p>
                            Alertas
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                </li>
                <!-- /.Users -->

                <!-- Contact -->
                <li class="nav-item nav-item-click cp">
                    <a class="nav-link">
                        <i class="nav-icon fas fa-exclamation-triangle"></i>
                        <p>
                            Configurações
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                </li>
                <!-- /.Users -->

                <!-- Contact -->
                <li class="nav-item">
                    <a href="<?= DEFAULT_BASE_PATH . 'login/logout' ?>" class="nav-link">
                        <i class="nav-icon fas fa-sign-out-alt"></i>
                        <p>
                            Sair
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                </li>
                <!-- /.Users -->
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>