<head>
    <!-- Meta Tags - Início -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Meta Tags - Fim -->

    <!-- Título da página - Início -->
    <!--  //$this->tag->getTitle(); ?> -->
    <!-- Título da página - Fim -->

    <!-- Estilização - Início -->
    <?php $this->assets->outputCss(); ?>
    <!-- Estilização - Fim -->

    <!-- Favicon - Início -->
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>
    <!-- Favicon - Fim -->
</head>