<header>
    <div class="header-mobile h-lg">
        <div class="row topnav ov-h pt-1 pl-1 pr-1">
            <div class="col-10">
            <a class="active" href="">
                <img src="https://radiustheme.com/demo/html/roofit/img/mobile-logo.png" alt="logo" class="img-fluid">
            </a>
            
            </div>
            <a href="javascript:void(0);" class="col-2 icon" onclick="myFunction()">
                <i class="fa fa-bars">=</i>
            </a>
            <div id="myLinks" class="col-12 swiper-scrollbar-lock bg-pm">
                <ul class="mt-1 mb-2">
                    <li><a href="" class="tx-wt bk tx-lg tx-tf-u">INÍCIO</a></li>
                    <li>
                       <a class="cp" href="">BUSCAR</a>
                    </li>
                    <li><a href="#" class="tx-wt bk tx-lg tx-tf-u">SERVICES</a></li>
                    <li><a href="#" class="tx-wt bk tx-lg tx-tf-u">BLOGS</a></li>
                    <li><a href="#" class="tx-wt bk tx-lg tx-tf-u">PAGES</a></li>
                    <li>
                        <a href="" class="tx-wt bk tx-lg tx-tf-u cp">CONTATO</a>
                    </li>
                </ul>
            </div>
            
        </div>
    </div>

    <div class="header-desktop v-lg">
        <!-- <div class="topbar  bg-pm tx-wt pt-1 pb-1 pl-6">

            <div class="ct-fl">
                <div class="row">
                    <div class="col-lg-2">
                        <p>E-mail: roofit@gmail.com</p>
                    </div>
                    <div class="col-lg-4">
                        <p><i class="far fa-clock"></i>Hours: Mon-Fri: 8.00 am - 7.00 pm</p>
                    </div>
                    <div class="col-lg-4">
                        <div class="header-topbar-layout1">
                            <div class="row header-top-right">
                                <p>+880-96-100</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div> -->
        <div class="ct-fl bg-wt tx-bk pt-1 pb-1 bs-card">
            <div class="row gt-md jf-ct-c al-it-c">
                <div class="col-3 tx-c">
                    <img src="https://radiustheme.com/demo/html/roofit/img/logo-dark.png" alt="">
                </div>
                <div class="col-6">
                    <ul class="row gt-1 gt-md-xl jf-ct-c ">
                        <li class="col-auto cp tx-dg-hv tx-b tx-tf-u">
                            <a class="cp" href="">INÍCIO</a>    
                        </li>
                        <li class="col-auto cp tx-dg-hv tx-b tx-tf-u">
                            <a class="cp" href="">BUSCAR</a>
                        </li>
                        <li class="col-auto cp tx-dg-hv tx-b tx-tf-u">SERVICE</li>
                        <li class="col-auto cp tx-dg-hv tx-b tx-tf-u">BLOGS</li>
                        <li class="col-auto cp tx-dg-hv tx-b tx-tf-u">PAGES</li>
                        <li class="col-auto cp tx-dg-hv tx-b tx-tf-u">
                            <a class="cp" href="">CONTATO</a>
                        </li>
                    </ul>
                </div>
                <div class="col-3">
                    <div class="row al-it-c gt-sm-xl">
                        <div class="col-auto">
                            <a href="" class="bd-st-sl bd-wd-1 bd-cl-ac tx-c tx-ac tx-b pt-md pb-md pl-1 pr-1 bd-rd-sm bg-ac-hv tx-wt-hv tx-tf-u">Entrar</a>
                        </div>
                        <div class="col-auto">
                            <a href="" class="bd-st-sl bd-wd-1 bd-cl-ac tx-c tx-ac tx-b pt-md pb-md pl-1 pr-1 bd-rd-sm bg-ac-hv tx-wt-hv tx-tf-u">Anunciar</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>