<div class="card card-primary">
    <div class="card-header text-center">
        <h3 class="card-title text-center">Orcamentos</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form role="form" class="budget-create">

        <div class="card-body">

            <div class="alert alert-warning alert-dismissible hd">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <div class="row">
                    <div class="col-auto">
                        <i class="icon fas fa-exclamation-triangle"></i>
                    </div>

                    <div class="col">
                        <div class="alert-message"></div>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label>Nome do cliente</label>

                <div class="input-group my-colorpicker2 colorpicker-element" data-colorpicker-id="2">
                    
                    <input type="text" class="form-control" id="client" value="" name="client" placeholder="Digite o cliente">
                    <ul class="client-list rl ul-list pl-3 pb-1 pt-1 cp hd" id="client-list"></ul>

                <div class="input-group-append new-client">
                    <span class="input-group-text"><i class="fas fa-user-plus mr-1"></i>Novo</span>
                </div>
                </div>
                <!-- /.input group -->
            </div>

            <div class="form-group phisical-group">
                <label for="cpf">CPF</label>
                <input type="text" class="form-control" name="cpf" placeholder="CPF">
            </div>

            <div class="form-group juridical-group ">
                <label for="nameCompany">Nome da empresa</label>
                <input type="text" class="form-control" name="nameCompany" placeholder="Nome da empresa">
            </div>

            <div class="form-group juridical-group hd">
                <label for="cnpj">CNPJ</label>
                <input type="text" class="form-control" name="cnpj" placeholder="CNPJ">
            </div>

            <div class="form-group phisical-group">
                <label>Data de nascimento:</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                        <i class="far fa-calendar-alt"></i>
                        </span>
                    </div>
                    <input type="text" class="form-control float-right" id="reservation" name="birthDate">
                </div>
                <!-- /.input group -->
            </div>

            <div class="form-group">
                <label for="email">Email</label>
                <input type="text" class="form-control" name="email" placeholder="email">
            </div>

            <div class="form-group">
                <label for="phone">Telefone</label>
                <input type="text" class="form-control" id="phone" placeholder="telefone">
            </div>

            <div class="form-group">
                <label>Cidade</label>
                <input type="text" class="form-control" id="cities" value="" name="cities" placeholder="Digite a cidade">
                <ul class="cities-list rl ul-list pl-3 pb-1 pt-1 cp hd" id="cities-list"></ul>
            </div>

            <div class="form-group">
                <label for="district">Bairro</label>
                <input type="text" class="form-control" name="district" placeholder="Bairro">
            </div>

            <div class="form-group">
                <label for="street">Rua</label>
                <input type="text" class="form-control" name="street" placeholder="rua">
            </div>

            <div class="form-group">
                <label for="number">Número</label>
                <input type="text" class="form-control" name="number" placeholder="Número">
            </div>

            <div class="form-group">
                <label for="complement">Complemento</label>
                <input type="text" class="form-control" name="complement" placeholder="Complemento">
            </div>

            <div class="form-group">
                <label for="zipCode">CEP</label>
                <input type="text" class="form-control" name="zipCode" placeholder="CEP">
            </div>

            <input type="hidden" name="userType" value="3">
        </div>
        <!-- /.card-body -->
        <div class="card-footer text-center">
            <button type="submit" class="btn btn-primary client-create-submit">Cadastrar</button>
        </div>
    </form>
</div>