<div class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="<?= DEFAULT_BASE_PATH ?>"><b>JoTek Instalações</b></a>
        </div>
        <!-- /.login-logo -->
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">Área Administrativa</p>

                <div class="tx-ac mb-2 tx-md-lg">
                    <?php echo $this->flashSession->output() ?>
                </div>
                <form  method="post" action="<?= DEFAULT_BASE_PATH . 'login/entrar' ?>">
                    <div class="input-group mb-3">
                        <input type="text" name="userName" class="form-control" placeholder="Usuário" value="<?= isset($userName) ? $userName : ''  ?>">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-user"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input type="password" name="password" class="form-control" placeholder="Senha">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-8">
                            <div class="icheck-primary">
                                <input type="checkbox" id="remember">
                                <label for="remember">Lembrar login</label>
                            </div>
                        </div>
                    </div>

                    <input type='hidden' name='<?= $this->security->getTokenKey() ?>' value='<?= $this->security->getToken() ?>'/>

                    <button type="submit" class="btn btn-block btn-danger mt-2">
                        <strong>ENTRAR</strong>
                    </button>
                
                </form>
                <!-- /.social-auth-links -->
                <p class="mb-1 mt-4">
                    <a href="forgot-password.html">Esqueceu a senha? Clique aqui</a>
                </p>
            </div>
            <!-- /.login-card-body -->
        </div>
    </div>
</div>